---
- name: add HTTPS apt access 
  apt:
    name: ["apt-transport-https", "ca-certificates", "curl", "gnupg", "lsb-release"]

- name: "Add docker gpg Key"
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    file: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present
  
- name: "Add Docker registery"
  BECOME: true
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    update_cache: true

- name: "install Docker dependencies"
  apt: 
    name: [docker-ce-cli, containerd.io]
    state: latest

- name: "Start Docker service"
  become: true
  systemd: 
    name: docker
    enabled: yes
    state: restarted 