---
- name: change docker file mode
  become: true
  become_method: sudo
  become_user: root 
  command: chmod 777 /var/run/docker.sock 
  # ansible.builtin.file:
  #   path: /var/run/docker.sock
  #   mode: '0644'

- name: Start Docker service
  systemd: 
    name: docker
    enabled: yes
    state: restarted 

- name: copy source files to server
  copy:
    src: "{{ item }}"
    dest: ./model_data/
  with_fileglob:
    - "/root/project/model_data/*"
  tags:
    - model-data

- name: copy other files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: 
    - { src: "~/project/Dockerfile", dest: "./Dockerfile" }
    - { src: "~/project/.dockerignore", dest: "./.dockerignore" }
    - { src: "~/project/make_prediction.sh", dest: "./make_prediction.sh" }
    - { src: "~/project/app.py", dest: "./app.py" }
    - { src: "~/project/requirements.txt", dest: "./requirements.txt" }
    - { src: "~/project/make_prediction.sh", dest: "./make_prediction.sh" }
  tags:
    - others

- name: Build image 
  docker_image:
    build:
      path: .
      pull: no
    name: pman06/ml
    tag: "{{ docker_tag }}"
    source: build
  tags:
    - build

- name: Start docker container
  docker_container:
    name: test-docker
    image: pman06/ml:{{ docker_tag }}
    ports:
     - "8000:80"
    detach: yes
    state: started
  tags:
    - start
    
- name: change docker file mode
  become: true
  become_method: sudo
  become_user: root 
  command: chmod 777 make_prediction.sh

- name: testing
  become: true
  command: 
    cmd: |
      result=$(./make_prediction.sh)
      echo $result | grep "prediction"
  tags:
    - testing

- name: remove container
  docker_container:
    name: test-docker
    state: absent